# Generated by Django 2.1.7 on 2019-04-08 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodblog', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='pic',
            field=models.ImageField(blank=True, null=True, upload_to='food_pic'),
        ),
    ]
